### PR TITLE
Add setting up gpg keys link to SIGNING_SECRET_KEY

### PR DESCRIPTION
**Pull request by glensc**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

Adds a link to how to setup gpg to secrets table.

This allows getting straight to the point without having to panic and being uncertain how to perform a specific task.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks!

**Comment by glensc** [comment]
This was a close hit! :)

You merged without waiting for CI to pass, but I had not signed DCO and the anchor link missed a `#`

NOTE to self: *always* start with a Draft, even if it's a trivial change, especially if it's a trivial change.

**Comment by Ocramius** [comment]
@glensc I don't really care that much about DCO unless it's a major feature. Indeed, I thought it was pointing to a file though :-\

**Comment by glensc** [comment]
@Ocramius but I managed to fix before merge, the correct commit was merged :)

**Comment by Ocramius** [comment]
Yeh, saw the push 👍

**Pull request merged**
