### PR TITLE
reduce semver version comparison complexity

### PR DESCRIPTION
**Pull request by bendavies**
REF: https://github.com/laminas/automatic-releases/pull/116#discussion_r582948617

This is not a bug fix. Let me know if you want a different branch.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Excellent, thanks!

**Comment by Ocramius** [comment]
@bendavies could you rebase this?

**Comment by bendavies** [comment]
rebased on 1.11.x

**Comment by Ocramius** [comment]
Thanks!

**Pull request merged**
